version: '3.8'

services:
  mongo:
    container_name: mongo-server
    image: mongo:latest
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./data/mongodb/mongod.conf:/etc/mongod.conf
      - ./data/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./data/mongodb/data/db/:/data/db/
    command: mongod --auth --port '${MONGO_PORT}' --dbpath /data/db
    networks:
      - common

  redis:
    container_name: redis-server
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./data/redis/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --requirepass '${REDIS_PASSWORD}' --appendonly yes --save "" --protected-mode no --dir /data
    networks:
      - common

networks:
  common:
    driver: bridge
